# aliases

alias k='kubectl'
alias kindmeup='kubectl config use-context kind-kind'
alias ll='ls -lahG'
alias vim='nvim'
alias loadGlobalProtect='launchctl load /Library/LaunchAgents/com.paloaltonetworks.gp.pangp*'
alias unloadGlobalProtect='launchctl unload /Library/LaunchAgents/com.paloaltonetworks.gp.pangp*'
alias gst='git status'

# path
export PATH="$PATH:/usr/local/bin:$HOME/go/bin"

# kubebuilder
export PATH="$PATH:/usr/local/kubebuilder/bin"

# cargo
export PATH="$PATH:$HOME/.cargo/bin"

# krew
export PATH="$PATH:$HOME/.krew/bin"

# gnu-sed
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

export GOPRIVATE=github.com/pivotal,gitlab.eng.vmware.com/services-control-plane

# bash-completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# z
. /usr/local/etc/profile.d/z.sh

# git-prompt
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
   __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
   source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi

# direnv
eval "$(direnv hook bash)"

# rbenv
eval "$(rbenv init -)"

# lastpass CLI timeout
export LPASS_AGENT_TIMEOUT=43200

# # java
# export PATH="/usr/local/opt/openjdk/bin:$PATH"

# # history
# export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
# export HISTSIZE=100000                   # big big history
# export HISTFILESIZE=100000               # big big history
# shopt -s histappend                      # append to history, don't overwrite it

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# private
if [ -f ~/.bash_private ]; then
   source ~/.bash_private
fi
